APP_NAME=recaply
APP_VERSION=0.0.2

STORAGE_PATH=storage


MONGODB_DATABASE=recaply
MONGODB_URI=
REDIS_URL=
QDRANT_URL=http://qdrant:6333



MAX_AUDIO_SIZE_MB=200
MAX_TEXT_SIZE_MB=10
MAX_SUBTITLE_SIZE_MB=20
MAX_PDF_SIZE_MB=50
TO_BYTES=1048576

CHUNK_OVERLAP=10
CHUNK_MIN_SIZE=150
CHUNK_MAX_SIZE=300
CHUNKS_SIMILARITY_THRESHOLD=0.75

COHERE_API_KEY=
LANGSMITH_API_KEY=
OPENAI_API_URL=https://openrouter.ai/api/v1
OPENAI_API_KEY=
LANGSMITH_API_KEY=

GENERATION_BACKEND=OPENAI
GENERATION_MODEL_ID=stepfun/step-3.5-flash:free

EMBEDDING_BACKEND=HF
EMBEDDING_MODEL_ID=all-MiniLM-L6-v2
EMBEDDING_MODEL_SIZE=384

TOP_K_DOCS=3

VECTOR_DB_BACKEND=QDRANT
VECTOR_DB_DISTANCE_METHOD=cosine